# Dependabot configuration:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    groups:
      gradle-deps:
        patterns:
        - "*"
    schedule:
      interval: "monthly"
    assignees:
      - "fstaudt"
    ignore:
      # commons-compress 1.28.0 introduced breaking changes in tar.gz extraction
      # Keep at 1.27.1 until the issue is resolved
      - dependency-name: "org.apache.commons:commons-compress"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "fstaudt"
    groups:
      github-actions:
        patterns:
        - "*"
