# Dependabot configuration:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    groups:
      gradle-deps:
        patterns:
        - "*"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "net.javacrumbs.json-unit:json-unit-assertj"
        versions: ["3.x"]
      - dependency-name: "org.jetbrains.intellij"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
        - "*"
