package io.github.fstaudt.helm

const val HELM_SCHEMA_FILE = "values.schema.json"
const val VALUES_SCHEMA_FILE = "values.schema.json"
const val PATCH_VALUES_SCHEMA_FILE = "values.schema.patch.json"
const val GLOBAL_VALUES_DEPRECATION = """"
Schema for global values is deprecated and will be removed in version 1.0.0.
It is only kept in download and aggregation for retro-compatibility with schemas generated by version 0.3.0.
Global values should instead be integrated in properties/global of values.schema.json.
"""
@Deprecated(GLOBAL_VALUES_DEPRECATION)
const val GLOBAL_VALUES_SCHEMA_FILE = "global-values.schema.json"

const val SCHEMA_VERSION = "https://json-schema.org/draft/2020-12/schema"

const val AGGREGATED_SCHEMA_FILE = "aggregated-values.schema.json"
const val PATCH_AGGREGATED_SCHEMA_FILE = "aggregated-values.schema.patch.json"
const val EMPTY = "\n\\n "
