name: Build
on:
  push:
    branches: [main,test]
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Fetch Sources"
        uses: actions/checkout@v3.1.0
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1.0.5
      - name: "Setup Java 11"
        uses: actions/setup-java@v3.7.0
        with:
          distribution: adopt
          java-version: 11
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: "Setup gradle wrapper"
        run: chmod +x gradlew
      - name: "Setup gradle"
        uses: gradle/gradle-build-action@v2.3.3
      - name: "Run Tests"
        run: ./gradlew check
      - name: "Collect Tests Result of failed tests"
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3.1.1
        with:
          name: tests-result
          path: ${{ github.workspace }}/build/reports/tests
      - name: "Sign shared library for mavenCentral"
        if: github.ref == 'refs/heads/main'
        run: ./gradlew :helm-values-shared:signMavenJavaPublication -Psigning.gnupg.keyName=${{ secrets.GPG_KEY_NAME }} -Psigning.gnupg.passphrase="${{ secrets.GPG_PASSPHRASE }}"
      - name: "Sign IntelliJ plugin for IntelliJ marketplace"
        if: github.ref == 'refs/heads/main'
        env:
          CERTIFICATE_CHAIN: ${{ secrets.INTELLIJ_CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.INTELLIJ_PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.INTELLIJ_PRIVATE_KEY_PASSWORD }}
        run: ./gradlew :helm-values-intellij-plugin:signPlugin
      - name: "Export Properties & products releases"
        id: properties
        shell: bash
        run: |
          PROPERTIES="$(./gradlew properties --console=plain -q)"
          VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')"
          NAME="$(echo "$PROPERTIES" | grep "^intellijPluginName:" | cut -f2- -d ' ')"

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "pluginVerifierHomeDir=~/.pluginVerifier" >> $GITHUB_OUTPUT

          ./gradlew :helm-values-intellij-plugin:listProductsReleases # prepare list of IDEs for Plugin Verifier
      - name: "Setup Plugin Verifier IDEs Cache"
        uses: actions/cache@v3.0.11
        with:
          path: ${{ steps.properties.outputs.pluginVerifierHomeDir }}/ides
          key: plugin-verifier-${{ hashFiles('helm-values-intellij-plugin/build/listProductsReleases.txt') }}
      - name: "Run IntelliJ Plugin Verification tasks"
        run: ./gradlew :helm-values-intellij-plugin:runPluginVerifier -Pplugin.verifier.home.dir=${{ steps.properties.outputs.pluginVerifierHomeDir }}
      - name: "Collect IntelliJ Plugin Verifier Result"
        if: ${{ always() }}
        uses: actions/upload-artifact@v3.1.1
        with:
          name: pluginVerifier-result
          path: ${{ github.workspace }}/helm-values-intellij-plugin/build/reports/pluginVerifier
      - name: "Prepare IntelliJ Plugin Artifact"
        id: artifact
        shell: bash
        run: |
          cd ${{ github.workspace }}/helm-values-intellij-plugin/build/distributions
          FILENAME="${{ steps.properties.outputs.name }}-${{ steps.properties.outputs.version }}"
          unzip "$FILENAME.zip" -d content
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT
      - name: "Upload IntelliJ Plugin Artifact"
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ steps.artifact.outputs.filename }}
          path: ./helm-values-intellij-plugin/build/distributions/content/*/*
