name: Build
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Fetch Sources"
        uses: actions/checkout@v3.0.2
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: "Setup Java 11"
        uses: actions/setup-java@v3.4.0
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - name: "Run Tests"
        run: chmod +x gradlew && ./gradlew check
      - name: "Collect Tests Result of failed tests"
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3.1.0
        with:
          name: tests-result
          path: ${{ github.workspace }}/build/reports/tests