name: Build
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Fetch Sources"
        uses: actions/checkout@v3.1.0
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1.0.5
      - name: "Setup Java 11"
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: "Setup gradle wrapper"
        run: chmod +x gradlew
      - name: "Run Tests"
        run: ./gradlew check
      - name: "Collect Tests Result of failed tests"
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3.1.0
        with:
          name: tests-result
          path: ${{ github.workspace }}/build/reports/tests
      - name: "Sign shared library for mavenCentral"
        if: github.ref == 'refs/heads/main'
        run: ./gradlew :helm-values-shared:signMavenJavaPublication -Psigning.gnupg.keyName=${{ secrets.GPG_KEY_NAME }} -Psigning.gnupg.passphrase="${{ secrets.GPG_PASSPHRASE }}"
      - name: "Qodana - Code Inspection"
        uses: JetBrains/qodana-action@v2022.2.3
      - name: "Export Properties & products releases"
        id: properties
        shell: bash
        run: |
          PROPERTIES="$(./gradlew properties --console=plain -q)"
          VERSION="$(echo "$PROPERTIES" | grep "^version:" | cut -f2- -d ' ')"
          NAME="$(echo "$PROPERTIES" | grep "^intellijPluginName:" | cut -f2- -d ' ')"

          echo "::set-output name=version::$VERSION"
          echo "::set-output name=name::$NAME"
          echo "::set-output name=pluginVerifierHomeDir::~/.pluginVerifier"

          ./gradlew :helm-values-intellij-plugin:listProductsReleases # prepare list of IDEs for Plugin Verifier
      - name: "Setup Plugin Verifier IDEs Cache"
        uses: actions/cache@v3.0.11
        with:
          path: ${{ steps.properties.outputs.pluginVerifierHomeDir }}/ides
          key: plugin-verifier-${{ hashFiles('helm-values-intellij-plugin/build/listProductsReleases.txt') }}
      - name: "Run IntelliJ Plugin Verification tasks"
        run: ./gradlew :helm-values-intellij-plugin:runPluginVerifier -Pplugin.verifier.home.dir=${{ steps.properties.outputs.pluginVerifierHomeDir }}
      - name: "Collect IntelliJ Plugin Verifier Result"
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: pluginVerifier-result
          path: ${{ github.workspace }}/helm-values-intellij-plugin/build/reports/pluginVerifier
      - name: "Prepare IntelliJ Plugin Artifact"
        id: artifact
        shell: bash
        run: |
          cd ${{ github.workspace }}/helm-values-intellij-plugin/build/distributions
          FILENAME=`ls *.zip`
          unzip "$FILENAME" -d content

          echo "::set-output name=filename::${FILENAME:0:-4}"
      - name: "Upload IntelliJ Plugin Artifact"
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ steps.artifact.outputs.filename }}
          path: ./helm-values-intellij-plugin/build/distributions/content/*/*
