name: Release
on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Fetch Sources"
        uses: actions/checkout@v3.0.2
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1.0.5
      - name: "Setup Java 11"
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: "Setup gradle wrapper"
        run: chmod +x gradlew
      - name: "Get version from tag"
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: "Publish shared library to mavenCentral"
        run: ./gradlew :helm-values-shared:publish :helm-values-shared:closeAndReleaseSonatypeStagingRepository -Pversion=${{ steps.version.outputs.VERSION }} -Psigning.gnupg.keyName=${{ secrets.GPG_KEY_NAME }} -Psigning.gnupg.passphrase="${{ secrets.GPG_PASSPHRASE }}" -PsonatypeUsername=${{ secrets.SONATYPE_USERNAME }} -PsonatypePassword="${{ secrets.SONATYPE_PASSWORD }}"
      - name: "Publish plugin"
        run: ./gradlew publishPlugins -Pversion=${{ steps.version.outputs.VERSION }} -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
      - name: "Create Release note"
        run: |
          awk -v ver="$1" '
            /^## / { if (p) { exit }; p=1; next } p && NF
          ' ./CHANGELOG.md > RELEASE.md
      - name: "Create release"
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE.md

