name: Release
on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Fetch Sources"
        uses: actions/checkout@v3.3.0
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: "Setup Java 11"
        uses: actions/setup-java@v3.10.0
        with:
          distribution: adopt
          java-version: 11
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: "Setup gradle wrapper"
        run: chmod +x gradlew
      - name: "Setup gradle"
        uses: gradle/gradle-build-action@v2.4.0
      - name: "Get version from tag"
        id: version
        run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - name: "Publish shared library to mavenCentral"
        run: ./gradlew :helm-values-shared:publish closeAndReleaseSonatypeStagingRepository -Pversion=${{ steps.version.outputs.version }} -Psigning.gnupg.keyName=${{ secrets.GPG_KEY_NAME }} -Psigning.gnupg.passphrase="${{ secrets.GPG_PASSPHRASE }}" -PsonatypeUsername=${{ secrets.SONATYPE_USERNAME }} -PsonatypePassword="${{ secrets.SONATYPE_PASSWORD }}"
      - name: "Publish gradle plugin to gradle plugin portal"
        run: ./gradlew publishPlugins -Pversion=${{ steps.version.outputs.version }} -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
      - name: "Publish IntelliJ plugin to IntelliJ marketplace"
        env:
          CERTIFICATE_CHAIN: ${{ secrets.INTELLIJ_CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.INTELLIJ_PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.INTELLIJ_PRIVATE_KEY_PASSWORD }}
          PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
        run: ./gradlew :helm-values-intellij-plugin:publishPlugin -Pversion=${{ steps.version.outputs.version }}
      - name: "Create Release note"
        run: |
          awk -v ver="$1" '
            /^## / { if (p) { exit }; p=1; next } p && NF
          ' ./CHANGELOG.md > RELEASE.md
      - name: "Create release"
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE.md

